### ISSUE TITLE
Failed to build on OpenBSD 7.3 AMD64

### ISSUE THREAD

**Issue by YisuiDenghua** [PrismLauncher/PrismLauncher#1301]
### Operating System

Other

### Version of Prism Launcher

Prism Launcher 7.1
Prism Launcher develop version

### Version of Qt

Qt 6.4.2

### Description of bug

When compiling Prism Launcher:

```
/home/yisui/PrismLauncher/launcher/FileSystem.cpp:106:10: fatal error: 'sys/attr.h' file not found
#include <sys/attr.h>
^~~~~~~~~~~~
1 error generated.
*** Error 1 in target 'launcher/CMakeFiles/Launcher_logic.dir/FileSystem.cpp.o'
*** Error 1 in . (launcher/CMakeFiles/Launcher_logic.dir/build.make:1348 'launcher/CMakeFiles/Launcher_logic.dir/FileSystem.cpp.o': cd /home...)
*** Error 2 in . (CMakeFiles/Makefile2:3239 'launcher/CMakeFiles/Launcher_logic.dir/all')
*** Error 2 in /home/yisui/PrismLauncher/build (Makefile:146 'all': make -s -f CMakeFiles/Makefile2 all)
```

### Steps to reproduce

1. Install Qt6, cmake, extra-cmake-modules, jdk, lwjgl, lwjgl3 to the system.
2. Build Prism Launcher following [build instructions](https://prismlauncher.org/wiki/development/build-instructions/#openbsd)
```
$ git clone --recursive https://github.com/PrismLauncher/PrismLauncher.git
$ cd PrismLauncher
$ git submodule init
$ git submodule update
$ mkdir install
$ cmake -S . -B build \
   -DCMAKE_INSTALL_PREFIX=./install -DCMAKE_PREFIX_PATH=/usr/local/lib/qt5/cmake -DENABLE_LTO=ON
$ cd build
$ make -j3 install

```

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Ryex** [comment]
are you sure this fails on develop?
we merged https://github.com/PrismLauncher/PrismLauncher/pull/1298 very reciently which should have fixed this

**Comment by YisuiDenghua** [comment]
> are you sure this fails on develop? we merged #1298 very reciently which should have fixed this

Sorry, I didn't update my local files. Now it's solved. Thanks.
