### PR TITLE
fix(SkinManageDialog): add missing QMenu include

### PR DESCRIPTION
**Pull request by parona-source**
launcher/ui/dialogs/skins/SkinManageDialog.cpp: In member function ‘void SkinManageDialog::show_context_menu(const QPoint&)’: launcher/ui/dialogs/skins/SkinManageDialog.cpp:344:18: error: variable ‘QMenu myMenu’ has initializer but incomplete type
  344 |     QMenu myMenu(tr("Context menu"), this);
      |                  ^~

Include appears to have been dropped transitively in either 0ba2c09787dbe3b852546dd24b437b832d575e4a or 45df360e4c751d30f8bfc38e5689f330e672492c

Not certain on the exact change but this failure came after https://github.com/PrismLauncher/PrismLauncher/pull/4502 was merged.

Are conventional commits preferred here? Or is any other specific style preferred?

I haven't checked the 10.x branch specifically, but its likely that this needs to be backported as well.

### CODE REVIEW

**Review by Trial97 — APPROVED** [review]

**Review by DioEgizio — APPROVED** [review]

**Review by TheKodeToad — APPROVED** [review]
I noticed this too when building without pre-compiled headers :/

It feels like this problem is cropping up a lot

**Comment by parona-source** [comment]
> I noticed this too when building without pre-compiled headers :/
> 
> It feels like this problem is cropping up a lot

Well its understandable as the move to precompiled headers + clean up is quite recent. Problems are inevitable with the previously implicit includes. Maybe include-what-you-use could be used pre-emptively but overdoing it might be an issue.

**Comment by DioEgizio** [comment]
we should disable pch in the codeql action so we don't accidentally break it, but that's outside the scope of this pr
